import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const menus = [
  { path: "/Home", name: "Home" },
  { path: "/Music", name: "Music" },
  { path: "/Gaming", name: "Gaming" },
  { path: "/Education", name: "Education" },
  { path: "/Science & Tech", name: "Science & Tech" },
  { path: "/Entertainment", name: "Entertainment" },
  { path: "/Student Hubs", name: "Student Hubs" },
];
// bg-[#161618]
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-full flex-col">
          <header className="h-11 bg-[#212227]">header</header>
          <main className="flex flex-1 overflow-auto bg-[#161618]">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <div className="flex h-full">
//           <nav className="w-60 bg-[#2C2F48] flex flex-col">
//             <div className="h-11 border-b">search-match-history</div>
//             <ul className="flex gap-2 px-3 py-4 flex-col flex-1 overflow-auto">
//               {menus.map((menu) => {
//                 return (
//                   <Link
//                     key={menu.path}
//                     className="text-[15px] p-2 text-[#FFFFFF] bg-[#000000]/50 rounded-md"
//                     href={menu.path}
//                   >
//                     {menu.name}
//                   </Link>
//                 );
//               })}
//             </ul>
//           </nav>
//           <div className="flex-1 flex flex-col">
//             <header className="h-11 bg-[##161618]">header</header>
//             <main className="flex-1 overflow-auto">{children}</main>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }
